---
- name: Install and start apache HTTPD
  hosts: webservers
  tasks: 
    - name: httpd package is present
      yum:
        name: httpd
        state: present
    - name: correct index.html is present
      copy: 
        src: index.html
        dest: /var/www/html/index.html
    - name: https is started
      service:
        name: httpd
        state: started
        enabled: true 
